### ISSUE TITLE
乱码问题如何解决

### ISSUE THREAD

**Issue by sundanping** [beezen/nucm#11]
安装后为什么只要使用nucm 就是一堆乱码（或者是二进制文件流在输出）
环境 Mac
node 16.0+
<img width="533" alt="截屏2022-10-08 14 13 23" src="https://user-images.githubusercontent.com/21334242/194692163-76827ea4-5842-4486-9331-f3c479772cf0.png">

**Comment by beezen** [comment]
> 安装后为什么只要使用nucm 就是一堆乱码（或者是二进制文件流在输出） 环境 Mac node 16.0+ <img alt="截屏2022-10-08 14 13 23" width="533" src="https://user-images.githubusercontent.com/21334242/194692163-76827ea4-5842-4486-9331-f3c479772cf0.png">
